Features/final-product
Wahaj-Ali/Portfolio pull request #7
Opened 2022-10-28 17:40 UTC by Wahaj-Ali

This is the final version of my portfolio(mobile-css-first approach). It is only front-end project. It contains .html and .css files. 
This project has the following features
- a header with a logo 
- a headline section with my information
- a works section 
- about me section
- get in touch section 
- social media contacts at the end

2022-10-28 18:45 UTC, Felix45 requested changes
Hi @Wahaj-Ali , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights :heavy_check_mark: 
- [ ] All linter checks are passing :white_check_mark: 
- [ ] Good descriptive and commit messages :white_check_mark: 
- [ ] Descriptive pull request title and summary :white_check_mark: 
- [ ] Correct use of Github flow :white_check_mark: 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 18:45 UTC, Felix45 commented on index.html
> +    <section class="container-works">
[Required] please consider displaying this `section` with `display: grid` since this is part of the project requirement. please see the screenshot below for more information.
<img src="https://user-images.githubusercontent.com/16392046/198704189-8c1e3291-f99a-466a-b4db-cc7421e24472.png" />

2022-10-28 18:45 UTC, Felix45 commented on index.html
> +    </section>
[ Required ] Please consider laying out each `<section class="works">` using `flexbox` as indicated in the project requirements. Please see the screenshot below for more information on this. 

<img src="https://user-images.githubusercontent.com/16392046/198704189-8c1e3291-f99a-466a-b4db-cc7421e24472.png" />

I also advise that each project title should be wrapped in an `h3` tag this is because the semantic `section` tag is usually accompanied by a `hx` tag in order to improve the readability of the page to users using web assistive technologies like screen readers.

2022-10-28 18:45 UTC, Felix45 commented on index.html
> +        <p id="about_text">About Me</p>
[ Required ] Please consider changing this `p` tag to an `h2` tag, given the size of text used on this `p` tag it would be better to have it as the heading for this section. It's usually advisable to use `hx` tags to mark the headings of sections instead of enlarging the font-size on a `p` tag.

2022-10-28 18:45 UTC, Felix45 commented on index.html
> +            </article>
[ Required ] Please consider changing this part of your app to a `ul` list, since this is a list of items it's not semantically right to use the `p` tag to wrap it please correct this.

2022-10-28 18:45 UTC, Felix45 commented on index.html
> +            </ul>
[ Required ] Please consider aligning the programming languages list as illustrated in the Figma template. As illustrated in the images below the languages list should align to the left and be inline with description text.

## Figma template
<img src="https://user-images.githubusercontent.com/16392046/198708741-249d7423-4075-494c-ad3b-c3fcb9a4d436.png" width="300px" />


## Current implementation
<img src="https://user-images.githubusercontent.com/16392046/198708360-bbd58611-69dd-4f87-b00d-6ccb4590f719.png" width="300px" />

2022-10-29 12:21 UTC, emmiiorji approved these changes
Hi @Wahaj-Ali, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

 
![congratulations](https://user-images.githubusercontent.com/20554583/197318511-6afdd6f2-aa6f-4da6-8061-4899dec8c651.gif)


## Good Highlights✔

- Linter checks are passing
- Good commit message
- Adherence to GitHub flow
- Required changes have been implemented

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 12:58 UTC, merged